# collect
data_path: data
file_name: raw_data.csv

# preprocess
max_window_size: 7
dataset_path: dataset
include_bonus: false

# train
input_dim: 45
output_dim: 45
split_ratio: 0.9
model_path: model
max_epoch: 77
shuffle: true
debug: true
max_evals: 16
## hyper parameters
learning_rate: 0.0001
batch_size: 64
hidden_dim: 64
early_stop_threshold: 7

# inference
count: 5
log_path: log