# collect
data_path: data
file_name: raw_data.csv

# preprocess
window_size: 7
dataset_path: dataset

# train
input_dim: 45
hidden_dim: 128
output_dim: 45
learning_rate: 0.0003
epoch: 77
batch_size: 64
split_ratio: 0.9
model_path: model

# inference
count: 5
log_path: log